spring.application.name=shopping-cart-API

server.port=8090

spring.jpa.hibernate.ddl-auto=update

# Swagger Config
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true



spring.servlet.multipart.max-file-size=5MB


spring.sql.init.mode=always
# logging.level.org.springframework=debug
#
#spring.security.user.name=abdo
#spring.security.user.password=1234

security.jwt.secret-key=dmVnZXRhYmxlYmFua2NlbnR1cnltZXJlbHlsZXR0ZXJhY3R1YWxseWV2ZXJ5dGhpbmc=
