spring.application.name=shopping-cart-API

server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5161/shopping-cart?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=Abdo@1152004
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql =true

spring.servlet.multipart.max-file-size=5MB


spring.sql.init.mode=always
logging.level.org.springframework=debug
#
#spring.security.user.name=abdo
#spring.security.user.password=1234

security.jwt.secret-key=dmVnZXRhYmxlYmFua2NlbnR1cnltZXJlbHlsZXR0ZXJhY3R1YWxseWV2ZXJ5dGhpbmc=

